import {
  LayoutDashboard,
  History,
  Users,
  FileSpreadsheet,
  Receipt,
  Calculator,
  CalendarDays,
  Settings,
  CreditCard,
  Clock,
  ShieldAlert,
  Megaphone,
  FileText,
  Briefcase,
  GraduationCap,
  Wallet,
  TrendingUp,
  Crown,
  Building2,
  Package,
  Building,
} from "lucide-react";
import type { MenuItem } from "./types";
import { PERMISSIONS } from "./permissions";

export const menuItems: MenuItem[] = [
  {
    title: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    permission: PERMISSIONS.VIEW_SELF_ATTENDANCE,
    group: "Menu Utama",
    hideForPlatformAdmin: true,
  },

  {
    title: "History Attendance",
    href: "/history",
    icon: History,
    permission: [PERMISSIONS.VIEW_SELF_ATTENDANCE],
    group: "Kehadiran",
    hideForPlatformAdmin: true,
  },
  {
    title: "Attendance Recap",
    href: "/admin/recap",
    icon: FileSpreadsheet,
    permission: PERMISSIONS.EXPORT_ATTENDANCE,
    group: "Kehadiran",
    hideForPlatformAdmin: true,
  },
  {
    title: "Overtime",
    href: "/overtime",
    icon: Clock,
    permission: [PERMISSIONS.VIEW_OVERTIME, PERMISSIONS.VIEW_SELF_OVERTIME],
    group: "Kehadiran",
    hideForPlatformAdmin: true,
  },

  {
    title: "Leave Request",
    href: "/leave",
    icon: CalendarDays,
    permission: [PERMISSIONS.VIEW_LEAVE, PERMISSIONS.VIEW_SELF_LEAVE],
    group: "Pengajuan",
    hideForPlatformAdmin: true,
  },
  {
    title: "Loan",
    href: "/loan",
    icon: CreditCard,
    permission: [PERMISSIONS.VIEW_LOAN, PERMISSIONS.VIEW_SELF_LOAN],
    group: "Pengajuan",
    hideForPlatformAdmin: true,
  },
  {
    title: "Asset Management",
    href: "/assets",
    icon: Package,
    permission: [PERMISSIONS.VIEW_ASSET, PERMISSIONS.VIEW_SELF_ASSET],
    group: "Pengajuan",
    hideForPlatformAdmin: true,
    requiredModule: "asset",
  },
  {
    title: "Reimbursement",
    href: "/reimbursement",
    icon: Receipt,
    permission: [PERMISSIONS.VIEW_REIMBURSEMENT, PERMISSIONS.VIEW_SELF_REIMBURSEMENT],
    group: "Pengajuan",
    hideForPlatformAdmin: true,
  },

  {
    title: "Finance",
    href: "/finance",
    icon: Wallet,
    permission: PERMISSIONS.VIEW_FINANCE,
    group: "Keuangan",
    hideForPlatformAdmin: true,
    requiredModule: "finance",
  },
  {
    title: "Finance Dashboard",
    href: "/finance/dashboard",
    icon: TrendingUp,
    permission: PERMISSIONS.VIEW_FINANCE_DASHBOARD,
    group: "Keuangan",
    hideForPlatformAdmin: true,
    requiredModule: "finance",
  },

  {
    title: "Employees",
    href: "/admin/employees",
    icon: Users,
    permission: PERMISSIONS.VIEW_EMPLOYEE,
    group: "Karyawan",
    hideForPlatformAdmin: true,
  },
  {
    title: "Contracts",
    href: "/admin/contracts",
    icon: FileText,
    permission: PERMISSIONS.VIEW_CONTRACT,
    group: "Karyawan",
    hideForPlatformAdmin: true,
    requiredModule: "contract",
  },
  {
    title: "Payrolls",
    href: "/admin/payrolls",
    icon: Calculator,
    permission: PERMISSIONS.VIEW_PAYROLL,
    group: "Karyawan",
    hideForPlatformAdmin: true,
    requiredModule: "payroll",
  },

  {
    title: "Recruitment",
    href: "/admin/requisitions",
    icon: Briefcase,
    permission: PERMISSIONS.VIEW_REQUISITION,
    group: "Rekrutmen",
    hideForPlatformAdmin: true,
    requiredModule: "recruitment",
  },
  {
    title: "Onboarding",
    href: "/admin/onboarding",
    icon: GraduationCap,
    permission: PERMISSIONS.VIEW_ONBOARDING,
    group: "Rekrutmen",
    hideForPlatformAdmin: true,
    requiredModule: "onboarding",
  },

  {
    title: "Company Settings",
    href: "/admin/company-settings",
    icon: Settings,
    permission: PERMISSIONS.VIEW_COMPANY,
    group: "Pengaturan",
    hideForPlatformAdmin: true,
  },
  {
    title: "Departments",
    href: "/admin/departments",
    icon: Building,
    permission: PERMISSIONS.VIEW_MASTER,
    group: "Pengaturan",
    hideForPlatformAdmin: true,
  },
  {
    title: "Roles & Permissions",
    href: "/admin/roles",
    icon: ShieldAlert,
    permission: PERMISSIONS.VIEW_ROLE,
    group: "Pengaturan",
    hideForPlatformAdmin: true,
  },
  {
    title: "Announcements",
    href: "/admin/announcements",
    icon: Megaphone,
    permission: PERMISSIONS.CREATE_ANNOUNCEMENT,
    group: "Pengaturan",
    hideForPlatformAdmin: true,
  },
  {
    title: "Dashboard",
    href: "/admin/platform-dashboard",
    icon: LayoutDashboard,
    group: "Platform",
    platformAdminOnly: true,
  },
  {
    title: "Companies",
    href: "/admin/companies",
    icon: Building2,
    group: "Platform",
    platformAdminOnly: true,
  },
  {
    title: "Subscriptions",
    href: "/admin/subscriptions",
    icon: Crown,
    group: "Platform",
    platformAdminOnly: true,
  },
  {
    title: "Request History",
    href: "/admin/subscription-history",
    icon: History,
    group: "Platform",
    platformAdminOnly: true,
  },
];
