export const PERMISSIONS = {
  // role & permission management
  VIEW_PERMISSION: "VIEW_PERMISSION",
  CREATE_ROLE: "CREATE_ROLE",
  VIEW_ROLE: "VIEW_ROLE",
  ASSIGN_ROLE: "ASSIGN_ROLE",

  // master
  VIEW_MASTER: "VIEW_MASTER",

  // employee
  VIEW_EMPLOYEE: "VIEW_EMPLOYEE",
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  EXPORT_EMPLOYEE: "EXPORT_EMPLOYEE",

  // attendance
  VIEW_ATTENDANCE: "VIEW_ATTENDANCE",
  VIEW_SELF_ATTENDANCE: "VIEW_SELF_ATTENDANCE",
  CREATE_ATTENDANCE: "CREATE_ATTENDANCE",
  EXPORT_ATTENDANCE: "EXPORT_ATTENDANCE",

  // payroll
  VIEW_PAYROLL: "VIEW_PAYROLL",
  GENERATE_PAYROLL: "GENERATE_PAYROLL",
  DOWNLOAD_PAYSLIP: "DOWNLOAD_PAYSLIP",
  MARK_AS_PAID: "MARK_AS_PAID",
  SEND_PAYSLIP: "SEND_PAYSLIP",

  // leave
  VIEW_LEAVE: "VIEW_LEAVE",
  VIEW_SELF_LEAVE: "VIEW_SELF_LEAVE",
  CREATE_LEAVE: "CREATE_LEAVE",
  APPROVAL_LEAVE: "APPROVAL_LEAVE",
  EXPORT_LEAVE: "EXPORT_LEAVE",

  // loan
  VIEW_LOAN: "VIEW_LOAN",
  VIEW_SELF_LOAN: "VIEW_SELF_LOAN",
  CREATE_LOAN: "CREATE_LOAN",
  APPROVAL_LOAN: "APPROVAL_LOAN",
  EXPORT_LOAN: "EXPORT_LOAN",

  // overtime
  VIEW_OVERTIME: "VIEW_OVERTIME",
  VIEW_SELF_OVERTIME: "VIEW_SELF_OVERTIME",
  CREATE_OVERTIME: "CREATE_OVERTIME",
  APPROVAL_OVERTIME: "APPROVAL_OVERTIME",
  EXPORT_OVERTIME: "EXPORT_OVERTIME",

  // reimbursement
  VIEW_REIMBURSEMENT: "VIEW_REIMBURSEMENT",
  VIEW_SELF_REIMBURSEMENT: "VIEW_SELF_REIMBURSEMENT",
  CREATE_REIMBURSEMENT: "CREATE_REIMBURSEMENT",
  APPROVAL_REIMBURSEMENT: "APPROVAL_REIMBURSEMENT",
  EXPORT_REIMBURSEMENT: "EXPORT_REIMBURSEMENT",

  // company
  VIEW_COMPANY: "VIEW_COMPANY",
  UPDATE_COMPANY: "UPDATE_COMPANY",

  // announcement
  CREATE_ANNOUNCEMENT: "CREATE_ANNOUNCEMENT",

  // contract
  VIEW_CONTRACT: "VIEW_CONTRACT",
  CREATE_CONTRACT: "CREATE_CONTRACT",
  UPDATE_CONTRACT: "UPDATE_CONTRACT",
  EXPORT_CONTRACT: "EXPORT_CONTRACT",

  // recruitment - requisitions
  VIEW_REQUISITION: "VIEW_REQUISITION",
  CREATE_REQUISITION: "CREATE_REQUISITION",
  APPROVAL_REQUISITION: "APPROVAL_REQUISITION",

  // recruitment - applicants
  VIEW_APPLICANT: "VIEW_APPLICANT",
  CREATE_APPLICANT: "CREATE_APPLICANT",
  UPDATE_APPLICANT: "UPDATE_APPLICANT",
} as const;

export type Permission = keyof typeof PERMISSIONS;
